### ISSUE TITLE
Make loader support mechanism extensible

### ISSUE THREAD

**Issue by ivd-git** [PySport/kloppy#13]
Now the loader support mechanism can download files from HTTP/HTTPS sources. Would be nice to make it extensible so that it can also load from S3 buckets or other locations.

At this branch there is some pseudo code to show how it could be implemented:
https://github.com/ivd-git/kloppy/tree/spike/loader-mechanism

**Comment by koenvo** [comment]
Cool! I this also related somehow to writing datasets? I can imagine I would like to read a dataset from provider A, do some transformations and then store it on S3, for later usage.

**Comment by pratikthanki** [comment]
@koenvo Hey, this looks cool - if no one is working on this I can look to kick it off? 😄

**Comment by koenvo** [comment]
@ivd-git do you remember how we thought this should work for both the ‘datasets’ (which loads public available datasets) and your own datasets? 

I think the Loader should be used in the helper functions and replace the current fetching code in https://github.com/PySport/kloppy/blob/master/kloppy/infra/datasets/core/loading.py#L40 . But especially for the first case we have to think about the caching. Possible options:
1. Download directly to memory (no caching)
2. Download to temp file (caching until host restart)
3. Download to home dir (caching until manual cleaned)

First implementation could be option 1 combined with 3: for public datasets enable option 3, and for your own datasets use 1. This way behavior for public datasets does not change.

**Comment by pratikthanki** [comment]
@koenvo based on my understanding of what you've said; could this be something that works with a throw-away Docker container running Influx/Redis or similar? 

It can serve as the mechanism to read data and write any analysis/transformations.

**Comment by koenvo** [comment]
@pratikthanki I would like to not introduce dependencies on docker containers. The implementation should be python.

The idea is that we add protocol handlers to be able to load data over plain http / s3 / gcp storage / etc by just adding a protocol to the filename. Instead of passing a local filename like "/home/koen/tracab.dat" I pass "s3://bucket-name/tracab.dat" and kloppy will load it from s3.

An example are the contrib submodules of luigi: https://luigi.readthedocs.io/en/stable/api/luigi.contrib.html .
