### ISSUE TITLE
IDs instead of [home, away, shirt_number]

### ISSUE THREAD

**Issue by bdagnino** [PySport/kloppy#17]
Currently while building the datasets, the way to reference a team is by [home, away], and the way to reference a player is by combining [home, away] with the shirt number. I believe when available in the data, it would be better to index by the team and players IDs. 

What are your thoughts on this?

**Comment by koenvo** [comment]
Good one. I would like to make this configurable. When combining data from different providers it easier to use shirt numbers.

For what use case would you like the provider ids?

OR implement https://github.com/PySport/kloppy/issues/3 and add a little helper / layer to go from shirt number to provider id.

I think I’d prefer the last one. Would that work for you?

**Comment by bdagnino** [comment]
By last one you mean "go for the provider ids by default and have a mapper to go to shirt numbers"? I'd agree with that. The game model on #3 could have field to specify which provider are the tracking and event from and that can be used in the mapper to go from ids to shirt number.

**Comment by koenvo** [comment]
Brainfart here for the internals: introduce a PlayerIdentifier type which holds IdentifierType (Jersey, Provider[Statsbomb], Provider[Metrica], etc) and the value. 

and use player_id instead of jersey_number everywhere. 

The PlayerIdentifier __eq__ method should check type and raise exception when types don't match. This will prevent mistakes when trying to match different types of identifiers

**Comment by koenvo** [comment]
Fixed in https://github.com/PySport/kloppy/pull/34
