### ISSUE TITLE
Enrich events with state

### ISSUE THREAD

**Issue by koenvo** [PySport/kloppy#48]
When filtering or creating windows of events it's useful to have additional state added to the events. This state can contain current score, lineup and other stuff like possession_id. 

I think we need something like this. With `state` added to `Event`.

```python

class StateReducer(metaclass=ABCMeta):
    @abstractmethod
    def get_initial_state(self):
        raise NotImplementedError

    @abstractmethod
    def reduce(self, current_state, event: Event):
        raise NotImplementedError


class PossessionTeamReducer(StateReducer):
    def get_initial_state(self):
        return None

    def reduce(self, current_state, event: Event):
        if event.event_type in ....:
            return event.team
        else:
            return current_state


def add_event_state(dataset: EventDataset, **state_reducers: Dict[str, StateReducer]) -> EventDataset:
    if not state_reducers:
        state_reducers = dict(
            possession_team=PossessionReducer(),
            score=ScoreReducer()
        )

    state_cls = make_dataclass('State', [(key, Any) for key in state_reducers.keys()])

    state = state_cls(**{
        key: reducer.get_initial_state()
        for key, reducer in state_reducers.items()
    })

    events = []
    for event in dataset.events:
        state =state_cls(** {
            key: reducer.reduce(getattr(state, key), event)
            for key, reducer in state_reducers.items()
        })
        event.state = state
        
    return replace(
        dataset,
        events=events
    )
```

**Comment by rjtavares** [comment]
@koenvo can you check my code to add possession_team to State based on the add_window branch: https://github.com/rjtavares/kloppy/commit/12e9d3fa67a16a19557363fa0240d6f99958bb58

I haven't tested it yet, it's just to validate the approach and naming.

**Comment by bdagnino** [comment]
@koenvo @rjtavares On important think to keep in mind is that events that loose possession are important as well. there can be quite some dead time between the end of a possession and the start of another one, so it'd could be also important to check fo events that end a possession. 

For example for Metrica events the events that start and end a possession are:
```python
START_EVENTS = ['RECOVERY', 'SET PIECE'];
END_EVENTS   = ['BALL OUT', 'BALL LOST', 'SHOT', 'FAULT RECEIVED'];
```

On a related topic: I'm aware this has been already discussed in the other issue, but I  think it's a better idea to try to include whatever van be inferred about each provider on the serializer itself, and then make the enrichment as as generic as possible, rather than the opposite as proposed by @koenvo in the previous ticket. 

The reasoning being that you'd expect as a user to have provider-dependent logic on the serializer itself, but not somewhere else like in the enricher. So for example in the case of the metrica serializer we could use what we know (from the above)  and then only change possession on those event types. Statbombs already has this info, and probably the same can be done with Opta and any other provider. 

Then

**Comment by koenvo** [comment]
Totally agree. Provider specific stuff should not leak out of the serializers. When I said otherwise it's my mistake.

possession_team should be part of the serializer, possession_id should be part of the enrichment process. Agree?

**Comment by bdagnino** [comment]
100%!

**Comment by rjtavares** [comment]
So it's best to focus first on adding possession_team to the serializers, then take care of State after that. I can make the pull request for Opta's serializer.

**Comment by koenvo** [comment]
Some more info: https://www.optasports.com/news/advanced-metrics-sequences-framework/

**Comment by koenvo** [comment]
Fixed in https://github.com/PySport/kloppy/pull/55
