### ISSUE TITLE
Include Skillcorner into Kloppy 

### ISSUE THREAD

**Issue by TK5-Tim** [PySport/kloppy#67]
Today Friends of Tracking and Skillcorner announced a [new open Dataset](https://github.com/SkillCorner/opendata) for Tracking Data. I just saw that [Tweet](https://twitter.com/numberstorm/status/1314238391609896960?s=20) about another different Format and immediately thought about Kloppy! 

So what would be needed to include Skillcorner into Kloppy? 

I am not that familiar yet with what everything is needed but I would be happy to help.

**Comment by koenvo** [comment]
Cool! Would be great to have it added the kloppy.

Maybe @hugobordigoni can help a bit here?

**Comment by hugobordigoni** [comment]
Great initiative 👍 
I'm not familiar with kloppy codebase. Not sure we'll have time to dive into it to create SkillCornerTrackingSerializer in the short term. Happy to help anyway if I can.

**Comment by hugobordigoni** [comment]
I feel like the main challenge here would be handling the tracking data with no player identification. Our data contains players with no identification, just a team identifier. Depending on what you want to do with the data, it's really important to keep it.

**Comment by TK5-Tim** [comment]
Would it be a good start to look what we can use from the Metrica Serializer and from there handle all the differences?

**Comment by koenvo** [comment]
The files seem pretty different. Output should be a TrackingDataset. Additional info https://twitter.com/thesignigame/status/1315996651178385409

Most difficult part is the player with only team identification. @hugobordigoni does it have an unique id to track the player over multiple frames? Could we use that one as a player identifier?

**Comment by hugobordigoni** [comment]
Indeed, when the player identity (trackable_object) is missing, we have a track_id. We could use that. There can be some conflict between track_id and trackable_object having the same value but seems doable.

**Comment by koenvo** [comment]
@TK5-Tim are you still interested in picking this up (together we me .. or @hugobordigoni ? :-))

**Comment by TK5-Tim** [comment]
@koenvo Yes for sure. I had a lot to do over the last week but should be better now :) But I would need some help for sure!

**Comment by znstrider** [comment]
@koenvo @TK5-Tim
I spent some time on this now and achieved building a TrackingDataset from the raw data.

As there are **a lot** of unidentified players with different track_id's it returns a (56754, 2226) DataFrame from to_pandas() for one of the sample games. For now I called the unidentified players '{team.ground}_anon_{track_id}'.

I haven't yet propely built the class and have not dealt with the logging and frame_rate parts etc, so there is still a good bit to do. I might need some help with those parts.
The code definitely needs some revising too and I would really like a code review at some point after I clean it up a bit in the coming days. Just wanted to let you know so you don't repeat the work. 

At the moment it's all in a notebook. What's the best way to share it for review and possibly further collaborate on this?

**Comment by znstrider** [comment]
I uploaded the SkillCornerTrackingSerializer in skillcorner.py, also adding a load_skillcorner_tracking_data on my fork:
https://github.com/znstrider/kloppy/tree/skillcornertrackingserializer

It works on all samples but there are quite a few issues that need adressing though:

#### 1)
sample_rate and limit still have to be implemented and attacking_direction_from_frame needs to be checked.

#### 2) ball_owning_player
A ball_owning_player can be specified by SkillCorner. Kloppy doesn't specify this as of now?

#### 3) z_coordinate of the ball
A z_coordinate of the ball is sometimes specified by SkillCorner. Do we want to create a new class Point3d?

#### 4) Handling of empty frames (data: []) due to lack of footage
I suppose we include them for means of interpolating etc?

#### 5) Handling PitchDimensions
In SkillCorner there are different pitch sizes specified, ie Anfield is 101 x 68m, I suppose that is reflected in the x variable ranging from -50.5 to 50.5?
Do you standardize pitch dimensions when loading them into kloppy or just set the PitchDimensions?
(ie. would we need to handle this on the {x|y}_per_meter in PitchDimensions?)

#### 6) ( question for @hugobordigoni )
In the game between Bayern München und Borussia Dortmund from 2019-11-09 [match_id = 2417] the list of frame dictionaries starts with a lot of period = None and data = [] dicts.

Then it has a few seconds of player data that is not yet part of the period. Is that pre game footage?

Then a little after, it has period: 1 and the time starts running, but data is still an empty list for > 20 seconds. Is that just the time running too early which we would have to manually check and adjust, or is / can this be footage missing with the actual game running already?

#### 7) Tests
I am wholly unfamiliar with testing as of now.

<br>

Any help and feedback would be appreciated.

**Comment by koenvo** [comment]
This is great! Let me have a look at it later this week.

**Comment by hugobordigoni** [comment]
@znstrider you're right. You have some pregame data at frame 1150, the period and time are null for these frames. Then the match starts at frame 1411. So the period and time are not null but there is no data because the broadcast is not with camera 1. Then at frame 1523 (11s after the start of the match) the broadcast uses camera 1.

I don't think it's an issue to drop all the pregame data if it does not exist in kloppy modelization.

**Comment by znstrider** [comment]
Thanks, @hugobordigoni.
That makes a lot of sense and I checked it again with the game footage.

I now leave out pregame data, but do include all frames that have a period specified, including those at the beginning that lack player positions due to a "wrong" camera perspective being used.

**Comment by koenvo** [comment]
I created a pull request to make it easier for me to review all the code: https://github.com/PySport/kloppy/pull/90/files
----

@znstrider, thanks for your contribution! Really cool to see how far you already got, and I believe we are near a version that can be merged. I tried to answer all your questions. If I missed something please let me know.

1) Comment about sample_rate is in the PullRequest

2) ball_owning_player
This is interesting. SkillCorner is the first provider that includes this information as far as I know. If you like you can add it. I do like the addition!

3) z-coordinate for the ball
Same. But that should be a separate issue because it also requires changes in Tracab and Metrica serializers (their data also includes z-coordinate for the ball). I create a issue for this: https://github.com/PySport/kloppy/issues/91

4) Handling of empty frames (data: []) due to lack of footage
I would like to leave them out for now. Could add some post-processing services later on to fix missing data for any dataset

5) Handling PitchDimensions
@bdagnino is working on this in PR https://github.com/PySport/kloppy/pull/87. @bdagnino can you give @znstrider some pointers here?

6) -

7) Tests
The automated tests help us to make sure the code covers some edge cases and help is to see when we unintentionally break existing code. The tests for serializers mostly exists of an input file that should be loadable, and a python file trying to load the input. I think a good start is to look at https://github.com/PySport/kloppy/blob/master/kloppy/tests/test_metrica.py. You can copy and paste it into test_skillcorner.py and replace the Metrica parts with SkillCorner.  The questions in this issue are good pointers for tests:
- Are empty frames skipped?
- Are anonymous players loaded correctly?
- Is pregame info skipped?
- Is pitchdimension set correctly?

**Comment by znstrider** [comment]
> **4) Handling of empty frames (data: []) due to lack of footage**
> I would like to leave them out for now. Could add some post-processing services later on to fix missing data for any dataset

Similar to the option "only_alive" in the TRACABSerializer I could specify an option "include_empty_frames" with the default being False to the deserialize function.
That would make it super simple to (not) include those frames. What do you think @koenvo?

**Comment by znstrider** [comment]
Thanks again for your comments @koenvo!
Especially the points on the testing made it much less daunting than it seemed.

Regarding 2)
I left out the ball_owning_player (ball_carrier) for now as that would've required to add ball_carrier to DataRecord and might require to add ball_carrier = None to all other serializers?

4) I added an option include_empty_frames = False to the deserialize function.

A couple of further questions I could use some help with:
I am unclear about the orientation included into the metadata and left it None.

Secondly, the skillcorner timestamps are 'mm:ss:ms' strings. I suppose they need to be converted to seconds, just like in metrica.py and tracab.py (DataRecord has it as float)?
